### ISSUE TITLE
mvn clean install issue

### ISSUE THREAD

**Issue by mitchelldehaven** [kermitt2/grobid-ner#65]
There was a previous issue under the same name a while back that I am now facing. I installed Grobid 0.6.0, built it using Gradle, then cloned grobid-ner from git moved the relevant directories over to Grobid 0.6.0. When running mvn clean install I get the following error message:

[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------------< org.grobid:grobid-ner >------------------------
[INFO] Building grobid-ner 0.6.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for org.grobid:grobid-core:jar:0.6.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.grobid:grobid-trainer:jar:0.6.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.282 s
[INFO] Finished at: 2020-06-10T14:21:13-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project grobid-ner: Could not resolve dependencies for project org.grobid:grobid-ner:jar:0.6.0-SNAPSHOT: The following artifacts could not be resolved: org.grobid:grobid-core:jar:0.6.0-SNAPSHOT, org.grobid:grobid-trainer:jar:0.6.0-SNAPSHOT: Failure to find org.grobid:grobid-core:jar:0.6.0-SNAPSHOT in file:////Users/mdehaven/software/grobid-0.6.0/grobid-ner/lib/ was cached in the local repository, resolution will not be reattempted until the update interval of 3rd-party-local-repo has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by lfoppiano** [comment]
when you build grobid, you should use `./gradlew clean install`. Did you do that? if you do only `clean build` won't install the dependencies.

**Comment by mitchelldehaven** [comment]
I ran "./gradlew clean install", but I ended up getting around the issue by changing the version from "0.6.0-SNAPSHOT" to "0.6.0". I'm not sure if that effectively does anything (I'm not familiar with how Maven works) or if something else I changed simultaneously that solved the problem. Now it is returning an error on 4 of the 17 tests: 

`Errors: 
[ERROR]   NERParserCommonTest.testresultExtraction_clusteror_simple:42 » IllegalArgument
[ERROR]   NERParserCommonTest.testresultExtraction_clusteror_simple2:71 » IllegalArgument
[ERROR]   NERParserTest.testExtractNE_en:38 » IllegalArgument No enum constant org.grobi...
[ERROR]   NERParserTest.testExtractNE_fr:55 » IllegalArgument No enum constant org.grobi...`

I'm going to dig a bit deeper into the errors to see if I can figure out what is going wrong.

**Comment by lfoppiano** [comment]
It seems something is going wrong in the tests... you could just build it by excluding the tests: `mvn clean install -DskipTests` 

Meanwhile, I'm checking what the problem is.

**Comment by lfoppiano** [comment]
If you run the tests, one problem is that you need to copy the grobid-ner models under grobid-home. 
Could you try that and let me know if it works?

**Comment by kermitt2** [comment]
This is fixed with branch `grobid-0.6.0` since a few days. I am waiting for the entity-fishing review to update everything at the same time.

**Comment by mitchelldehaven** [comment]
> If you run the tests, one problem is that you need to copy the grobid-ner models under grobid-home.
> Could you try that and let me know if it works?

I think I did this with "cp -r /path/to/grobid-ner/grobid-home/models/* /path/to/grobid-0.6.0/grobid-home/models" prior to trying to run the tests.

**Comment by mitchelldehaven** [comment]
> This is fixed with branch `grobid-0.6.0` since a few days. I am waiting for the entity-fishing review to update everything at the same time. @mitchelldehaven in between you can simply use this branch to avoid the build error and use Grobid latest stable release.

Thanks, I'll try that out and see if I still get the test errors.

**Comment by mitchelldehaven** [comment]
Using the grobid-0.6.0 branch with the stable grobid branch worked like a charm, all tests passed. Thanks!
